CREATE SCHEMA IF NOT EXISTS analyzer;

CREATE TABLE IF NOT EXISTS analyzer.user_action (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
user_id BIGINT NOT NULL,
event_id BIGINT NOT NULL,
user_score DOUBLE PRECISION NOT NULL,
timestamp_action TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS analyzer.event_similarity (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
event_a BIGINT NOT NULL,
event_b BIGINT NOT NULL,
score DOUBLE PRECISION NOT NULL
);