CREATE SCHEMA IF NOT EXISTS request;

CREATE TABLE IF NOT EXISTS request.participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP,
    event_id BIGINT,
    requester_id BIGINT,
    status VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
    );