server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

      routes:

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/v1/admin/users/**, /admin/users/**
          filters:
            - StripPrefix=0

        - id: location-service-route
          uri: lb://location-service
          predicates:
            - Path=/public/location/**, /admin/location/**
          filters:
             - StripPrefix=0

        - id: event-service-route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /events/**, /users/*/events/**, /categories/**, /compilations/**, /admin/categories/**, /admin/compilations/**
          filters:
             - StripPrefix=0

        - id: request-service-route
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**, internal/users/{userId}/events/{eventId}/requests/**
            - StripPrefix=0

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

