server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:

        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
          filters:
            - PrefixPath=/api/v1
            - StripPrefix=0

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/**
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

