CREATE SCHEMA IF NOT EXISTS events;

CREATE TABLE IF NOT EXISTS events.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit INT DEFAULT 0,
    request_moderation BOOLEAN DEFAULT FALSE,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    state VARCHAR(20) DEFAULT 'PENDING',
    published_on TIMESTAMP,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id BIGINT REFERENCES events.categories,
    initiator_id BIGINT,
    confirmed_requests INTEGER,
    CONSTRAINT chk_status CHECK (state IN ('PENDING', 'REJECTED', 'PUBLISHED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS events.compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE CHECK (length(title) >= 1),
    pinned BOOLEAN DEFAULT FALSE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS events.compilation_events(
    compilation_id BIGINT NOT NULL REFERENCES events.compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events.events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
    );

CREATE OR REPLACE FUNCTION events.distance(lat1 float, lon1 float, lat2 float, lon2 float)
    RETURNS float
AS
'
    declare
        dist float = 0;
        rad_lat1 float;
        rad_lat2 float;
        theta float;
        rad_theta float;
    BEGIN
        IF lat1 = lat2 AND lon1 = lon2
        THEN
            RETURN dist;
        ELSE
            -- переводим градусы широты в радианы
            rad_lat1 = pi() * lat1 / 180;
            -- переводим градусы долготы в радианы
            rad_lat2 = pi() * lat2 / 180;
            -- находим разность долгот
            theta = lon1 - lon2;
            -- переводим градусы в радианы
            rad_theta = pi() * theta / 180;
            -- находим длину ортодромии
            dist = sin(rad_lat1) * sin(rad_lat2) + cos(rad_lat1) * cos(rad_lat2) * cos(rad_theta);

            IF dist > 1
            THEN dist = 1;
            END IF;

            dist = acos(dist);
            -- переводим радианы в градусы
            dist = dist * 180 / pi();
            -- переводим градусы в километры
            dist = dist * 60 * 1.8524;

            RETURN dist;
        END IF;
    END;
'
    LANGUAGE PLPGSQL;