CREATE SCHEMA IF NOT EXISTS location;

CREATE TABLE IF NOT EXISTS location.location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    latitude FLOAT NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude FLOAT NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    radius FLOAT DEFAULT 0 CHECK (radius >=0),
    type VARCHAR(40) NOT NULL,
    CONSTRAINT chk_type CHECK (type IN ('CONFERENCE_HALL',
                                        'OPEN_AIR',
                                        'COWORKING',
                                        'STADIUM',
                                        'THEATER',
                                        'RESTAURANT',
                                         'OTHER'))
);

CREATE OR REPLACE FUNCTION location.distance(lat1 float, lon1 float, lat2 float, lon2 float)
RETURNS float AS $$
DECLARE
dist float = 0;
    rad_lat1 float;
    rad_lat2 float;
    theta float;
    rad_theta float;
BEGIN
    IF lat1 = lat2 AND lon1 = lon2 THEN
        RETURN dist;
ELSE
        rad_lat1 = pi() * lat1 / 180;
        rad_lat2 = pi() * lat2 / 180;
        theta = lon1 - lon2;
        rad_theta = pi() * theta / 180;
        dist = sin(rad_lat1) * sin(rad_lat2) + cos(rad_lat1) * cos(rad_lat2) * cos(rad_theta);
        IF dist > 1 THEN
            dist = 1;
END IF;
        dist = acos(dist);
        dist = dist * 180 / pi();
        dist = dist * 60 * 1.8524;
RETURN dist;
END IF;
END;
$$ LANGUAGE plpgsql;