CREATE SCHEMA IF NOT EXISTS location;

CREATE TABLE IF NOT EXISTS location.location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    latitude FLOAT NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude FLOAT NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    radius FLOAT DEFAULT 0 CHECK (radius >=0),
    type VARCHAR(40) NOT NULL,
    CONSTRAINT chk_type CHECK (type IN ('CONFERENCE_HALL',
                                        'OPEN_AIR',
                                        'COWORKING',
                                        'STADIUM',
                                        'THEATER',
                                        'RESTAURANT',
                                         'OTHER'))
);