DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP,
    event_id BIGINT NOT NULL,
    requester_id BIGINT,
    status VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
    );