<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>ru.practicum</groupId>
        <artifactId>explore-with-me</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>stats</artifactId>
    <packaging>pom</packaging>
    <modules>
        <module>aggregator</module>
        <module>analyzer</module>
        <module>collector</module>
        <module>serialization</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <avro.version>1.11.3</avro.version>
        <kafka-clients.version>3.6.1</kafka-clients.version>
        <protobuf.version>3.23.4</protobuf.version>
        <grpc.version>1.63.0</grpc.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <avro-maven-plugin.version>1.11.3</avro-maven-plugin.version>
        <protobuf-plugin.version>2.4.0</protobuf-plugin.version>
    </properties>

</project>